#if defined(DXMT_WSI_SDL3)
SDL_PROC(const SDL_DisplayMode*, SDL_GetClosestFullscreenDisplayMode, (SDL_DisplayID, int, int, float, bool))
SDL_PROC(const SDL_DisplayMode*, SDL_GetCurrentDisplayMode, (SDL_DisplayID))
SDL_PROC(const SDL_DisplayMode*, SDL_GetDesktopDisplayMode, (SDL_DisplayID))
SDL_PROC(bool, SDL_GetDisplayBounds, (SDL_DisplayID, SDL_Rect*))
SDL_PROC(SDL_DisplayMode**, SDL_GetFullscreenDisplayModes, (SDL_DisplayID, int*))
SDL_PROC(const char*, SDL_GetError, (void))
SDL_PROC(SDL_DisplayID*, SDL_GetDisplays, (int*))
SDL_PROC(SDL_DisplayID, SDL_GetDisplayForWindow, (SDL_Window*))
SDL_PROC(bool, SDL_SetWindowFullscreenMode, (SDL_Window*, const SDL_DisplayMode*))
SDL_PROC(bool, SDL_SetWindowFullscreen, (SDL_Window*, bool))
SDL_PROC(SDL_WindowFlags, SDL_GetWindowFlags, (SDL_Window*))
SDL_PROC(bool, SDL_GetWindowSize, (SDL_Window*, int*, int*))
SDL_PROC(bool, SDL_SetWindowSize, (SDL_Window*, int, int))
SDL_PROC(SDL_MetalView, SDL_Metal_CreateView, (SDL_Window*))
SDL_PROC(void*, SDL_Metal_GetLayer, (SDL_MetalView))
SDL_PROC(void, SDL_free, (void*))
#undef SDL_PROC
#endif // defined(DXMT_WSI_SDL3)
