
#pragma once

#include "d3d11_device.hpp"

#include "Metal/MTLCommandBuffer.hpp"
#include "Metal/MTLRenderCommandEncoder.hpp"

MIDL_INTERFACE("3a3f085a-d0fe-4324-b0ae-fe04de18571c")
IMTLD3D11DeviceContext : public ID3D11DeviceContext1 {

  virtual void STDMETHODCALLTYPE Flush2(
      std::function<void(MTL::CommandBuffer *)> && beforeCommit) = 0;
};
__CRT_UUID_DECL(IMTLD3D11DeviceContext, 0x3a3f085a, 0xd0fe, 0x4324, 0xb0, 0xae,
                0xfe, 0x04, 0xde, 0x18, 0x57, 0x1c);

namespace dxmt {

IMTLD3D11DeviceContext *NewD3D11DeviceContext(IMTLD3D11Device *device);

constexpr MTL::PrimitiveType g_topology_map[] = {
    // D3D11_PRIMITIVE_TOPOLOGY_UNDEFINED = 0,
    MTL::PrimitiveTypePoint,
    // D3D11_PRIMITIVE_TOPOLOGY_POINTLIST = 1,
    MTL::PrimitiveTypePoint,
    // D3D11_PRIMITIVE_TOPOLOGY_LINELIST = 2,
    MTL::PrimitiveTypeLine,
    // D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP = 3,
    MTL::PrimitiveTypeLineStrip,
    // D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST = 4,
    MTL::PrimitiveTypeTriangle,
    // D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP = 5,
    MTL::PrimitiveTypeTriangleStrip,
    // ADJ: & 0b1000
    // D3D11_PRIMITIVE_TOPOLOGY_LINELIST_ADJ = 10,
    // D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ = 11,
    // D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ = 12,
    // D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ = 13,
    // PATCHLIST: 32 + control point count
    // D3D11_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST = 33,
    // D3D11_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST = 34,
    // D3D11_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST = 35,
    // D3D11_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST = 36,
    // D3D11_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST = 37,
    // D3D11_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST = 38,
    // D3D11_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST = 39,
    // D3D11_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST = 40,
    // D3D11_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST = 41,
    // D3D11_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST = 42,
    // D3D11_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST = 43,
    // D3D11_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST = 44,
    // D3D11_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST = 45,
    // D3D11_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST = 46,
    // D3D11_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST = 47,
    // D3D11_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST = 48,
    // D3D11_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST = 49,
    // D3D11_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST = 50,
    // D3D11_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST = 51,
    // D3D11_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST = 52,
    // D3D11_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST = 53,
    // D3D11_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST = 54,
    // D3D11_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST = 55,
    // D3D11_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST = 56,
    // D3D11_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST = 57,
    // D3D11_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST = 58,
    // D3D11_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST = 59,
    // D3D11_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST = 60,
    // D3D11_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST = 61,
    // D3D11_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST = 62,
    // D3D11_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST = 63,
    // D3D11_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST = 64
};

} // namespace dxmt