#include "./d3d11_names.hpp"

std::ostream &operator<<(std::ostream &os, D3D_FEATURE_LEVEL e) {
  switch (e) {
    ENUM_NAME(D3D_FEATURE_LEVEL_9_1);
    ENUM_NAME(D3D_FEATURE_LEVEL_9_2);
    ENUM_NAME(D3D_FEATURE_LEVEL_9_3);
    ENUM_NAME(D3D_FEATURE_LEVEL_10_0);
    ENUM_NAME(D3D_FEATURE_LEVEL_10_1);
    ENUM_NAME(D3D_FEATURE_LEVEL_11_0);
    ENUM_NAME(D3D_FEATURE_LEVEL_11_1);
    ENUM_NAME(D3D_FEATURE_LEVEL_12_0);
    ENUM_NAME(D3D_FEATURE_LEVEL_12_1);
    ENUM_DEFAULT(e);
  }
}

std::ostream &operator<<(std::ostream &os, D3D11_RESOURCE_DIMENSION e) {
  switch (e) {
    ENUM_NAME(D3D11_RESOURCE_DIMENSION_UNKNOWN);
    ENUM_NAME(D3D11_RESOURCE_DIMENSION_BUFFER);
    ENUM_NAME(D3D11_RESOURCE_DIMENSION_TEXTURE1D);
    ENUM_NAME(D3D11_RESOURCE_DIMENSION_TEXTURE2D);
    ENUM_NAME(D3D11_RESOURCE_DIMENSION_TEXTURE3D);
    ENUM_DEFAULT(e);
  }
}
