lib_d3d12=cpp.find_library('d3d12')
lib_dxgi=cpp.find_library('dxgi')
inc=include_directories('../../src/d3d12')
executable('d3d12_basic',['d3d12_basic.cpp'],dependencies:[lib_d3d12,lib_dxgi],include_directories:[dxmt_include_path,inc],gui_app:false)
executable('d3d12_m3_resource',['d3d12_m3_resource.cpp'],dependencies:[lib_d3d12,lib_dxgi],include_directories:[dxmt_include_path,inc],gui_app:false)
executable('d3d12_m4_descriptor_heap',['d3d12_m4_descriptor_heap.cpp'],dependencies:[lib_d3d12,lib_dxgi],include_directories:[dxmt_include_path,inc],gui_app:false)
executable('d3d12_m6_m7_pso',['d3d12_m6_m7_pso.cpp'],dependencies:[lib_d3d12,lib_dxgi],include_directories:[dxmt_include_path,inc],gui_app:false)
executable('d3d12_m8_fence',['d3d12_m8_fence.cpp'],dependencies:[lib_d3d12,lib_dxgi],include_directories:[dxmt_include_path,inc],gui_app:false)
executable('d3d12_m9_texture',['d3d12_m9_texture.cpp'],dependencies:[lib_d3d12,lib_dxgi],include_directories:[dxmt_include_path,inc],gui_app:false)
executable('d3d12_m10_swapchain',['d3d12_m10_swapchain.cpp'],dependencies:[lib_d3d12,lib_dxgi],include_directories:[dxmt_include_path,inc],gui_app:false)
lib_d3dcompiler=cpp.find_library('d3dcompiler_47')
executable('d3d12_m11_shader',['d3d12_m11_shader.cpp'],dependencies:[lib_d3d12,lib_dxgi,lib_d3dcompiler],include_directories:[dxmt_include_path,inc],gui_app:false)
executable('d3d12_m5_triangle',['d3d12_m5_triangle.cpp'],dependencies:[lib_d3d12,lib_dxgi,lib_d3dcompiler],include_directories:[dxmt_include_path,inc],gui_app:false)
